sudo: false

language: sh

addons:
  apt:
    packages:
    - ghc
    - cabal-install

env:
    - PATH="$HOME/.cabal/bin:$PATH"

branches:
    only:
        - 166MMX-patch-1

before_script:
    - git clone 'https://github.com/koalaman/shellcheck.git' shellcheck
    - cd shellcheck; cabal update; cabal install
    - which shellcheck

script:
    - shellcheck -s sh letsencrypt.sh
