sudo: false

language: shell

branches:
    only:
        - 166MMX-patch-1

addons:
    apt:
        sources:
            - debian-sid    # Grab shellcheck from the Debian repo (o_O)
        packages:
            - shellcheck

script:
    - shellcheck -- letsencrypt.sh
