sudo: false

language: shell

addons:
  apt:
    packages:
    - ghc
    - cabal-install

env:
    - SHELLCHECK_VERSION="v0.4.3" PATH="$HOME/.cabal/bin:$PATH"

branches:
    only:
        - 166MMX-patch-1

before_script:
    - cabal update
    - git clone 'https://github.com/koalaman/shellcheck.git'
    - cd -- shellcheck
    - git checkout "$SHELLCHECK_VERSION" --
    - cabal configure
    - cabal build
    - cabal install

script:
    - shellcheck -s sh letsencrypt.sh
