sudo: false

language: shell

addons:
  apt:
    packages:
    - ghc
    - cabal-install

env:
    - VERSION="v0.4.3"

branches:
    only:
        - 166MMX-patch-1

before_script:
    - export PATH="$HOME/.cabal/bin:$PATH"
    - ghc --version
    - cabal --version
    - cabal update
    - git clone 'https://github.com/koalaman/shellcheck.git'
    - cd shellcheck
    - git checkout "$VERSION"
    - cabal install --only-dependencies 
    - cabal configure
    - cabal build
    - cabal install

script:
    - shellcheck -s sh letsencrypt.sh
